//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTeDiv.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICotedivServices")]
    public interface ICotedivServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/getPosts", ReplyAction="http://tempuri.org/ICotedivServices/getPostsResponse")]
        string[] getPosts(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/getPosts", ReplyAction="http://tempuri.org/ICotedivServices/getPostsResponse")]
        System.Threading.Tasks.Task<string[]> getPostsAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/getRanking", ReplyAction="http://tempuri.org/ICotedivServices/getRankingResponse")]
        string[] getRanking();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/getRanking", ReplyAction="http://tempuri.org/ICotedivServices/getRankingResponse")]
        System.Threading.Tasks.Task<string[]> getRankingAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICotedivServicesChannel : CoTeDiv.ServiceReference1.ICotedivServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CotedivServicesClient : System.ServiceModel.ClientBase<CoTeDiv.ServiceReference1.ICotedivServices>, CoTeDiv.ServiceReference1.ICotedivServices {
        
        public CotedivServicesClient() {
        }
        
        public CotedivServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CotedivServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotedivServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotedivServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getPosts(int idUsuario) {
            return base.Channel.getPosts(idUsuario);
        }
        
        public System.Threading.Tasks.Task<string[]> getPostsAsync(int idUsuario) {
            return base.Channel.getPostsAsync(idUsuario);
        }
        
        public string[] getRanking() {
            return base.Channel.getRanking();
        }
        
        public System.Threading.Tasks.Task<string[]> getRankingAsync() {
            return base.Channel.getRankingAsync();
        }
    }
}
