//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion1()
        {
            this.ElementoDireccions = new HashSet<ElementoDireccion>();
            this.Telefonoes = new HashSet<Telefono>();
        }
    
        public int Id { get; set; }
        public int IdNegocio { get; set; }
        public Nullable<int> IdLocacion { get; set; }
        public int IdStatus { get; set; }
        public int IdTipoLocal { get; set; }
    
        public virtual Locacion Locacion { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementoDireccion> ElementoDireccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefono> Telefonoes { get; set; }
        public virtual Negocio Negocio { get; set; }
        public virtual TipoLocal TipoLocal { get; set; }
    }
}
