//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foto1
    {
        public int Id { get; set; }
        public string URL { get; set; }
        public string Descripcion { get; set; }
        public int IdOferta { get; set; }
        public bool EsCarrousel { get; set; }
    
        public virtual Oferta Oferta { get; set; }
    }
}
