//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NegocioEtiqueta
    {
        public int Id { get; set; }
        public int IdNegocio { get; set; }
        public int IdEtiqueta { get; set; }
    
        public virtual Etiqueta Etiqueta { get; set; }
        public virtual Negocio Negocio { get; set; }
    }
}
