//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oferta()
        {
            this.Foto1 = new HashSet<Foto1>();
        }
    
        public int Id { get; set; }
        public int IdTipoOferta { get; set; }
        public string Nombre { get; set; }
        public string Breve { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int IdNegocio { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto1> Foto1 { get; set; }
        public virtual Negocio Negocio { get; set; }
        public virtual TipoOferta TipoOferta { get; set; }
    }
}
