//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusSistema
    {
        public int Id { get; set; }
        public int IdSistema { get; set; }
        public int IdStatus { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Sistema Sistema { get; set; }
        public virtual Status Status { get; set; }
    }
}
