//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TiendasEntities : DbContext
    {
        public TiendasEntities()
            : base("name=TiendasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Locacion> Locacions { get; set; }
        public virtual DbSet<Sistema> Sistemas { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatusSistema> StatusSistemas { get; set; }
        public virtual DbSet<TipoElemento> TipoElementoes { get; set; }
        public virtual DbSet<Direccion> Direccions { get; set; }
        public virtual DbSet<Foto> Fotoes { get; set; }
        public virtual DbSet<Nombre> Nombres { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Permiso> Permisoes { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<RolPermiso> RolPermisoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UsuarioSistema> UsuarioSistemas { get; set; }
        public virtual DbSet<Contacto> Contactoes { get; set; }
        public virtual DbSet<Direccion1> Direccion1 { get; set; }
        public virtual DbSet<ElementoDireccion> ElementoDireccions { get; set; }
        public virtual DbSet<Etiqueta> Etiquetas { get; set; }
        public virtual DbSet<Foto1> Foto1 { get; set; }
        public virtual DbSet<Negocio> Negocios { get; set; }
        public virtual DbSet<NegocioEtiqueta> NegocioEtiquetas { get; set; }
        public virtual DbSet<Oferta> Ofertas { get; set; }
        public virtual DbSet<Telefono> Telefonoes { get; set; }
        public virtual DbSet<TipoLocal> TipoLocals { get; set; }
        public virtual DbSet<TipoOferta> TipoOfertas { get; set; }
    }
}
