//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class etiqueta1
    {
        public int id { get; set; }
        public int idnegocio { get; set; }
        public int idetiqueta { get; set; }
    
        public virtual etiqueta etiqueta { get; set; }
        public virtual negocio negocio { get; set; }
    }
}
