//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class negocio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public negocio()
        {
            this.contactoes = new HashSet<contacto>();
            this.etiquetas = new HashSet<etiqueta1>();
            this.negocioplantillas = new HashSet<negocioplantilla>();
            this.ofertas = new HashSet<oferta>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string urllogo { get; set; }
        public int idpropietario { get; set; }
        public int idstatus { get; set; }
    
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contacto> contactoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etiqueta1> etiquetas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<negocioplantilla> negocioplantillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<oferta> ofertas { get; set; }
        public virtual propietario propietario { get; set; }
    }
}
