//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferta
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public bool mostrarprecio { get; set; }
        public int idnegocio { get; set; }
        public int idtipooferta { get; set; }
        public int idstatus { get; set; }
    
        public virtual status status { get; set; }
        public virtual negocio negocio { get; set; }
        public virtual tipooferta tipooferta { get; set; }
    }
}
