//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seccionplantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seccionplantilla()
        {
            this.negocioplantillas = new HashSet<negocioplantilla>();
        }
    
        public int id { get; set; }
        public int idplantilla { get; set; }
        public int idseccion { get; set; }
        public int idstatus { get; set; }
    
        public virtual plantilla plantilla { get; set; }
        public virtual seccion seccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<negocioplantilla> negocioplantillas { get; set; }
        public virtual status status { get; set; }
    }
}
