//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiendas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TiendasEntities : DbContext
    {
        public TiendasEntities()
            : base("name=TiendasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<etiqueta> etiquetas { get; set; }
        public virtual DbSet<localidad> localidads { get; set; }
        public virtual DbSet<plantilla> plantillas { get; set; }
        public virtual DbSet<seccion> seccions { get; set; }
        public virtual DbSet<seccionplantilla> seccionplantillas { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<negocio> negocios { get; set; }
        public virtual DbSet<propietario> propietarios { get; set; }
        public virtual DbSet<contacto> contactoes { get; set; }
        public virtual DbSet<etiqueta1> etiquetas1 { get; set; }
        public virtual DbSet<negocioplantilla> negocioplantillas { get; set; }
        public virtual DbSet<oferta> ofertas { get; set; }
        public virtual DbSet<tipolocalidad> tipolocalidads { get; set; }
        public virtual DbSet<tipooferta> tipoofertas { get; set; }
        public virtual DbSet<tipostatu> tipostatus { get; set; }
        public virtual DbSet<tipoubicacion> tipoubicacions { get; set; }
    }
}
