//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess.Cotediv
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cotedivEntities : DbContext
    {
        public cotedivEntities()
            : base("name=cotedivEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumno { get; set; }
        public virtual DbSet<Escuela> Escuela { get; set; }
        public virtual DbSet<EscuelaUbicacion> EscuelaUbicacion { get; set; }
        public virtual DbSet<Experto> Experto { get; set; }
        public virtual DbSet<ExpertoGrados> ExpertoGrados { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<PersonaDetalle> PersonaDetalle { get; set; }
        public virtual DbSet<Catalogo> Catalogo { get; set; }
        public virtual DbSet<TipoCatalogo> TipoCatalogo { get; set; }
        public virtual DbSet<EvaluacionPublicaciones> EvaluacionPublicaciones { get; set; }
        public virtual DbSet<Publicaciones> Publicaciones { get; set; }
        public virtual DbSet<Opiniones> Opiniones { get; set; }
    }
}
