//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SernaSistemas.DataAccess.Cotediv
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPublicaciones
    {
        public int IdPublicacion { get; set; }
        public System.Guid IdExperto { get; set; }
        public int IdValor { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Experto Experto { get; set; }
        public virtual Catalogo Catalogo { get; set; }
        public virtual Publicaciones Publicaciones { get; set; }
    }
}
