//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoTeDiv.CotedivServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CotedivServiceReference.ICotedivServices")]
    public interface ICotedivServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/Login", ReplyAction="http://tempuri.org/ICotedivServices/LoginResponse")]
        WCFCotedivLib.Contracts.LoginResponse Login(WCFCotedivLib.Contracts.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/Login", ReplyAction="http://tempuri.org/ICotedivServices/LoginResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.LoginResponse> LoginAsync(WCFCotedivLib.Contracts.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/Logout", ReplyAction="http://tempuri.org/ICotedivServices/LogoutResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.LoginRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BaseRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.LoginResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BoolResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.EntradaRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.EntradaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.ListaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.PerfilRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.PerfilResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.AlumnoRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.AlumnoResponse))]
        WCFCotedivLib.Contracts.BoolResponse Logout(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/Logout", ReplyAction="http://tempuri.org/ICotedivServices/LogoutResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.BoolResponse> LogoutAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/GuardarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/GuardarEntradaResponse")]
        WCFCotedivLib.Contracts.EntradaResponse GuardarEntrada(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/GuardarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/GuardarEntradaResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> GuardarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/VerEntrada", ReplyAction="http://tempuri.org/ICotedivServices/VerEntradaResponse")]
        WCFCotedivLib.Contracts.EntradaResponse VerEntrada(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/VerEntrada", ReplyAction="http://tempuri.org/ICotedivServices/VerEntradaResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> VerEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/BorrarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/BorrarEntradaResponse")]
        WCFCotedivLib.Contracts.BoolResponse BorrarEntrada(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/BorrarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/BorrarEntradaResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.BoolResponse> BorrarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/ListarEntradas", ReplyAction="http://tempuri.org/ICotedivServices/ListarEntradasResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.LoginRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BaseRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.LoginResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BoolResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.EntradaRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.EntradaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.ListaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.PerfilRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.PerfilResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.AlumnoRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.AlumnoResponse))]
        WCFCotedivLib.Contracts.ListaResponse ListarEntradas(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/ListarEntradas", ReplyAction="http://tempuri.org/ICotedivServices/ListarEntradasResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.ListaResponse> ListarEntradasAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/ValorarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/ValorarEntradaResponse")]
        WCFCotedivLib.Contracts.EntradaResponse ValorarEntrada(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/ValorarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/ValorarEntradaResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> ValorarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/EvaluarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/EvaluarEntradaResponse")]
        WCFCotedivLib.Contracts.EntradaResponse EvaluarEntrada(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/EvaluarEntrada", ReplyAction="http://tempuri.org/ICotedivServices/EvaluarEntradaResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> EvaluarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/GuardarPerfil", ReplyAction="http://tempuri.org/ICotedivServices/GuardarPerfilResponse")]
        WCFCotedivLib.Contracts.PerfilResponse GuardarPerfil(WCFCotedivLib.Contracts.PerfilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/GuardarPerfil", ReplyAction="http://tempuri.org/ICotedivServices/GuardarPerfilResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.PerfilResponse> GuardarPerfilAsync(WCFCotedivLib.Contracts.PerfilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/VerPerfil", ReplyAction="http://tempuri.org/ICotedivServices/VerPerfilResponse")]
        WCFCotedivLib.Contracts.PerfilResponse VerPerfil(WCFCotedivLib.Contracts.PerfilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/VerPerfil", ReplyAction="http://tempuri.org/ICotedivServices/VerPerfilResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.PerfilResponse> VerPerfilAsync(WCFCotedivLib.Contracts.PerfilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/ListarExpertos", ReplyAction="http://tempuri.org/ICotedivServices/ListarExpertosResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.LoginRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BaseRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.LoginResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BaseResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.BoolResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.EntradaRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.EntradaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.ListaResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.PerfilRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.PerfilResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.AlumnoRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WCFCotedivLib.Contracts.AlumnoResponse))]
        WCFCotedivLib.Contracts.ListaResponse ListarExpertos(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/ListarExpertos", ReplyAction="http://tempuri.org/ICotedivServices/ListarExpertosResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.ListaResponse> ListarExpertosAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/CrearCuenta", ReplyAction="http://tempuri.org/ICotedivServices/CrearCuentaResponse")]
        WCFCotedivLib.Contracts.AlumnoResponse CrearCuenta(WCFCotedivLib.Contracts.AlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICotedivServices/CrearCuenta", ReplyAction="http://tempuri.org/ICotedivServices/CrearCuentaResponse")]
        System.Threading.Tasks.Task<WCFCotedivLib.Contracts.AlumnoResponse> CrearCuentaAsync(WCFCotedivLib.Contracts.AlumnoRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICotedivServicesChannel : CoTeDiv.CotedivServiceReference.ICotedivServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CotedivServicesClient : System.ServiceModel.ClientBase<CoTeDiv.CotedivServiceReference.ICotedivServices>, CoTeDiv.CotedivServiceReference.ICotedivServices {
        
        public CotedivServicesClient() {
        }
        
        public CotedivServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CotedivServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotedivServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotedivServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCFCotedivLib.Contracts.LoginResponse Login(WCFCotedivLib.Contracts.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.LoginResponse> LoginAsync(WCFCotedivLib.Contracts.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public WCFCotedivLib.Contracts.BoolResponse Logout(object request) {
            return base.Channel.Logout(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.BoolResponse> LogoutAsync(object request) {
            return base.Channel.LogoutAsync(request);
        }
        
        public WCFCotedivLib.Contracts.EntradaResponse GuardarEntrada(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.GuardarEntrada(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> GuardarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.GuardarEntradaAsync(request);
        }
        
        public WCFCotedivLib.Contracts.EntradaResponse VerEntrada(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.VerEntrada(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> VerEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.VerEntradaAsync(request);
        }
        
        public WCFCotedivLib.Contracts.BoolResponse BorrarEntrada(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.BorrarEntrada(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.BoolResponse> BorrarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.BorrarEntradaAsync(request);
        }
        
        public WCFCotedivLib.Contracts.ListaResponse ListarEntradas(object request) {
            return base.Channel.ListarEntradas(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.ListaResponse> ListarEntradasAsync(object request) {
            return base.Channel.ListarEntradasAsync(request);
        }
        
        public WCFCotedivLib.Contracts.EntradaResponse ValorarEntrada(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.ValorarEntrada(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> ValorarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.ValorarEntradaAsync(request);
        }
        
        public WCFCotedivLib.Contracts.EntradaResponse EvaluarEntrada(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.EvaluarEntrada(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.EntradaResponse> EvaluarEntradaAsync(WCFCotedivLib.Contracts.EntradaRequest request) {
            return base.Channel.EvaluarEntradaAsync(request);
        }
        
        public WCFCotedivLib.Contracts.PerfilResponse GuardarPerfil(WCFCotedivLib.Contracts.PerfilRequest request) {
            return base.Channel.GuardarPerfil(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.PerfilResponse> GuardarPerfilAsync(WCFCotedivLib.Contracts.PerfilRequest request) {
            return base.Channel.GuardarPerfilAsync(request);
        }
        
        public WCFCotedivLib.Contracts.PerfilResponse VerPerfil(WCFCotedivLib.Contracts.PerfilRequest request) {
            return base.Channel.VerPerfil(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.PerfilResponse> VerPerfilAsync(WCFCotedivLib.Contracts.PerfilRequest request) {
            return base.Channel.VerPerfilAsync(request);
        }
        
        public WCFCotedivLib.Contracts.ListaResponse ListarExpertos(object request) {
            return base.Channel.ListarExpertos(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.ListaResponse> ListarExpertosAsync(object request) {
            return base.Channel.ListarExpertosAsync(request);
        }
        
        public WCFCotedivLib.Contracts.AlumnoResponse CrearCuenta(WCFCotedivLib.Contracts.AlumnoRequest request) {
            return base.Channel.CrearCuenta(request);
        }
        
        public System.Threading.Tasks.Task<WCFCotedivLib.Contracts.AlumnoResponse> CrearCuentaAsync(WCFCotedivLib.Contracts.AlumnoRequest request) {
            return base.Channel.CrearCuentaAsync(request);
        }
    }
}
